model:
  openai:
    key:
    chat_url: https://api.openai-hk.com/v1/chat/completions
    chat_max_tokens: 4096
    chat_model: gpt-3.5-turbo-1106
    chat_temperature: 1
    chat_top_p: 1
    chat_presence_penalty: 2
    chat_frequency_penalty: 0.4
    chat_prompt:
    embeddings_url: https://api.openai-hk.com/v1/embeddings
    embeddings_model: text-embedding-ada-002
  fastapi:
    test: null
