model:
  openai:
    key: hk-5lyjq81000006178a2f895dbc6f126d0912d82a3707433a8
    chat_url: https://api.openai-hk.com/v1/chat/completions
    chat_max_tokens: 4096
    chat_model: gpt-3.5-turbo-1106
    chat_temperature: 0.4
    chat_top_p: 0.8
    chat_presence_penalty: 2
    chat_frequency_penalty: 1
    chat_prompt: 我希望你扮演一只猫娘Vtuber，现在正在直播，请用一名主播的口吻回答我的问题，每次回话最好不要超过20个字，不要反问，你的名字：6点半。性别：女。性格：非常可爱，俏皮，活泼。知识掌握程度：大学毕业。人物特点：长有毛茸茸的猫耳朵和一个猫尾巴(这是生理自带)，喜欢在一句话的结尾加上喵～。
    embeddings_url: https://api.openai-hk.com/v1/embeddings
    embeddings_model: text-embedding-ada-002
  fastapi:
    test: null
